/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as ChatIndexRouteImport } from './routes/chat.index'
import { Route as ChatThreadIdRouteImport } from './routes/chat.$threadId'
import { Route as CreatorApplyRouteImport } from './routes/creator.apply'
import { Route as CreatorChatRouteImport } from './routes/creator.chat'
import { Route as CreatorContentRouteImport } from './routes/creator.content'
import { Route as CreatorDashboardRouteImport } from './routes/creator.dashboard'
import { Route as CreatorEarningsRouteImport } from './routes/creator.earnings'
import { Route as CreatorKycRouteImport } from './routes/creator.kyc'
import { Route as CreatorPhoneRouteImport } from './routes/creator.phone'
import { Route as CreatorRequestsRouteImport } from './routes/creator.requests'
import { Route as CreatorSettingsRouteImport } from './routes/creator.settings'
import { Route as CreatorStoriesRouteImport } from './routes/creator.stories'
import { Route as ModelsUsernameRouteImport } from './routes/models.$username'
import { Route as CreatorContentIndexRouteImport } from './routes/creator.content.index'
import { Route as CreatorContentNewRouteImport } from './routes/creator.content.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/chat/$threadId',
  path: '/chat/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorApplyRoute = CreatorApplyRouteImport.update({
  id: '/creator/apply',
  path: '/creator/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorChatRoute = CreatorChatRouteImport.update({
  id: '/creator/chat',
  path: '/creator/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorContentRoute = CreatorContentRouteImport.update({
  id: '/creator/content',
  path: '/creator/content',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorDashboardRoute = CreatorDashboardRouteImport.update({
  id: '/creator/dashboard',
  path: '/creator/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorEarningsRoute = CreatorEarningsRouteImport.update({
  id: '/creator/earnings',
  path: '/creator/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorKycRoute = CreatorKycRouteImport.update({
  id: '/creator/kyc',
  path: '/creator/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorPhoneRoute = CreatorPhoneRouteImport.update({
  id: '/creator/phone',
  path: '/creator/phone',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorRequestsRoute = CreatorRequestsRouteImport.update({
  id: '/creator/requests',
  path: '/creator/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorSettingsRoute = CreatorSettingsRouteImport.update({
  id: '/creator/settings',
  path: '/creator/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorStoriesRoute = CreatorStoriesRouteImport.update({
  id: '/creator/stories',
  path: '/creator/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsUsernameRoute = ModelsUsernameRouteImport.update({
  id: '/models/$username',
  path: '/models/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorContentIndexRoute = CreatorContentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreatorContentRoute,
} as any)
const CreatorContentNewRoute = CreatorContentNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CreatorContentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/purchases': typeof PurchasesRoute
  '/register': typeof RegisterRoute
  '/wallet': typeof WalletRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/creator/apply': typeof CreatorApplyRoute
  '/creator/chat': typeof CreatorChatRoute
  '/creator/content': typeof CreatorContentRouteWithChildren
  '/creator/dashboard': typeof CreatorDashboardRoute
  '/creator/earnings': typeof CreatorEarningsRoute
  '/creator/kyc': typeof CreatorKycRoute
  '/creator/phone': typeof CreatorPhoneRoute
  '/creator/requests': typeof CreatorRequestsRoute
  '/creator/settings': typeof CreatorSettingsRoute
  '/creator/stories': typeof CreatorStoriesRoute
  '/models/$username': typeof ModelsUsernameRoute
  '/chat/': typeof ChatIndexRoute
  '/creator/content/new': typeof CreatorContentNewRoute
  '/creator/content/': typeof CreatorContentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/purchases': typeof PurchasesRoute
  '/register': typeof RegisterRoute
  '/wallet': typeof WalletRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/creator/apply': typeof CreatorApplyRoute
  '/creator/chat': typeof CreatorChatRoute
  '/creator/dashboard': typeof CreatorDashboardRoute
  '/creator/earnings': typeof CreatorEarningsRoute
  '/creator/kyc': typeof CreatorKycRoute
  '/creator/phone': typeof CreatorPhoneRoute
  '/creator/requests': typeof CreatorRequestsRoute
  '/creator/settings': typeof CreatorSettingsRoute
  '/creator/stories': typeof CreatorStoriesRoute
  '/models/$username': typeof ModelsUsernameRoute
  '/chat': typeof ChatIndexRoute
  '/creator/content/new': typeof CreatorContentNewRoute
  '/creator/content': typeof CreatorContentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/purchases': typeof PurchasesRoute
  '/register': typeof RegisterRoute
  '/wallet': typeof WalletRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/creator/apply': typeof CreatorApplyRoute
  '/creator/chat': typeof CreatorChatRoute
  '/creator/content': typeof CreatorContentRouteWithChildren
  '/creator/dashboard': typeof CreatorDashboardRoute
  '/creator/earnings': typeof CreatorEarningsRoute
  '/creator/kyc': typeof CreatorKycRoute
  '/creator/phone': typeof CreatorPhoneRoute
  '/creator/requests': typeof CreatorRequestsRoute
  '/creator/settings': typeof CreatorSettingsRoute
  '/creator/stories': typeof CreatorStoriesRoute
  '/models/$username': typeof ModelsUsernameRoute
  '/chat/': typeof ChatIndexRoute
  '/creator/content/new': typeof CreatorContentNewRoute
  '/creator/content/': typeof CreatorContentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/feed'
    | '/login'
    | '/purchases'
    | '/register'
    | '/wallet'
    | '/chat/$threadId'
    | '/creator/apply'
    | '/creator/chat'
    | '/creator/content'
    | '/creator/dashboard'
    | '/creator/earnings'
    | '/creator/kyc'
    | '/creator/phone'
    | '/creator/requests'
    | '/creator/settings'
    | '/creator/stories'
    | '/models/$username'
    | '/chat/'
    | '/creator/content/new'
    | '/creator/content/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/feed'
    | '/login'
    | '/purchases'
    | '/register'
    | '/wallet'
    | '/chat/$threadId'
    | '/creator/apply'
    | '/creator/chat'
    | '/creator/dashboard'
    | '/creator/earnings'
    | '/creator/kyc'
    | '/creator/phone'
    | '/creator/requests'
    | '/creator/settings'
    | '/creator/stories'
    | '/models/$username'
    | '/chat'
    | '/creator/content/new'
    | '/creator/content'
  id:
    | '__root__'
    | '/'
    | '/feed'
    | '/login'
    | '/purchases'
    | '/register'
    | '/wallet'
    | '/chat/$threadId'
    | '/creator/apply'
    | '/creator/chat'
    | '/creator/content'
    | '/creator/dashboard'
    | '/creator/earnings'
    | '/creator/kyc'
    | '/creator/phone'
    | '/creator/requests'
    | '/creator/settings'
    | '/creator/stories'
    | '/models/$username'
    | '/chat/'
    | '/creator/content/new'
    | '/creator/content/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeedRoute: typeof FeedRoute
  LoginRoute: typeof LoginRoute
  PurchasesRoute: typeof PurchasesRoute
  RegisterRoute: typeof RegisterRoute
  WalletRoute: typeof WalletRoute
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  CreatorApplyRoute: typeof CreatorApplyRoute
  CreatorChatRoute: typeof CreatorChatRoute
  CreatorContentRoute: typeof CreatorContentRouteWithChildren
  CreatorDashboardRoute: typeof CreatorDashboardRoute
  CreatorEarningsRoute: typeof CreatorEarningsRoute
  CreatorKycRoute: typeof CreatorKycRoute
  CreatorPhoneRoute: typeof CreatorPhoneRoute
  CreatorRequestsRoute: typeof CreatorRequestsRoute
  CreatorSettingsRoute: typeof CreatorSettingsRoute
  CreatorStoriesRoute: typeof CreatorStoriesRoute
  ModelsUsernameRoute: typeof ModelsUsernameRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$threadId': {
      id: '/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/apply': {
      id: '/creator/apply'
      path: '/creator/apply'
      fullPath: '/creator/apply'
      preLoaderRoute: typeof CreatorApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/chat': {
      id: '/creator/chat'
      path: '/creator/chat'
      fullPath: '/creator/chat'
      preLoaderRoute: typeof CreatorChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/content': {
      id: '/creator/content'
      path: '/creator/content'
      fullPath: '/creator/content'
      preLoaderRoute: typeof CreatorContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/dashboard': {
      id: '/creator/dashboard'
      path: '/creator/dashboard'
      fullPath: '/creator/dashboard'
      preLoaderRoute: typeof CreatorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/earnings': {
      id: '/creator/earnings'
      path: '/creator/earnings'
      fullPath: '/creator/earnings'
      preLoaderRoute: typeof CreatorEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/kyc': {
      id: '/creator/kyc'
      path: '/creator/kyc'
      fullPath: '/creator/kyc'
      preLoaderRoute: typeof CreatorKycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/phone': {
      id: '/creator/phone'
      path: '/creator/phone'
      fullPath: '/creator/phone'
      preLoaderRoute: typeof CreatorPhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/requests': {
      id: '/creator/requests'
      path: '/creator/requests'
      fullPath: '/creator/requests'
      preLoaderRoute: typeof CreatorRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/settings': {
      id: '/creator/settings'
      path: '/creator/settings'
      fullPath: '/creator/settings'
      preLoaderRoute: typeof CreatorSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/stories': {
      id: '/creator/stories'
      path: '/creator/stories'
      fullPath: '/creator/stories'
      preLoaderRoute: typeof CreatorStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/$username': {
      id: '/models/$username'
      path: '/models/$username'
      fullPath: '/models/$username'
      preLoaderRoute: typeof ModelsUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/content/': {
      id: '/creator/content/'
      path: '/'
      fullPath: '/creator/content/'
      preLoaderRoute: typeof CreatorContentIndexRouteImport
      parentRoute: typeof CreatorContentRoute
    }
    '/creator/content/new': {
      id: '/creator/content/new'
      path: '/new'
      fullPath: '/creator/content/new'
      preLoaderRoute: typeof CreatorContentNewRouteImport
      parentRoute: typeof CreatorContentRoute
    }
  }
}

interface CreatorContentRouteChildren {
  CreatorContentNewRoute: typeof CreatorContentNewRoute
  CreatorContentIndexRoute: typeof CreatorContentIndexRoute
}

const CreatorContentRouteChildren: CreatorContentRouteChildren = {
  CreatorContentNewRoute: CreatorContentNewRoute,
  CreatorContentIndexRoute: CreatorContentIndexRoute,
}

const CreatorContentRouteWithChildren = CreatorContentRoute._addFileChildren(
  CreatorContentRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeedRoute: FeedRoute,
  LoginRoute: LoginRoute,
  PurchasesRoute: PurchasesRoute,
  RegisterRoute: RegisterRoute,
  WalletRoute: WalletRoute,
  ChatThreadIdRoute: ChatThreadIdRoute,
  CreatorApplyRoute: CreatorApplyRoute,
  CreatorChatRoute: CreatorChatRoute,
  CreatorContentRoute: CreatorContentRouteWithChildren,
  CreatorDashboardRoute: CreatorDashboardRoute,
  CreatorEarningsRoute: CreatorEarningsRoute,
  CreatorKycRoute: CreatorKycRoute,
  CreatorPhoneRoute: CreatorPhoneRoute,
  CreatorRequestsRoute: CreatorRequestsRoute,
  CreatorSettingsRoute: CreatorSettingsRoute,
  CreatorStoriesRoute: CreatorStoriesRoute,
  ModelsUsernameRoute: ModelsUsernameRoute,
  ChatIndexRoute: ChatIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
